### ISSUE TITLE
[Nice to have] Send the email ciphered

### ISSUE THREAD

**Issue by chervaliery** [GOVCERT-LU/GCNotify#1]
It would be great if the email could be sent ciphered (in a zip file with 'infected' as password for example).
This would ensure the email is not block or removed later when anti virus signatures are updated.

Nice work by the way.

**Comment by jhemp** [comment]
Thank you for the positive answer, I will take this into consideration and keep you updated with the results

**Comment by JorgeGHS** [comment]
Hi. 

Im having some problems trying to install it. Where is the Manifest file?

**Comment by jhemp** [comment]
@JorgeGHS I will continue the talk in issue #2
